version: '2'

services:
  scepserver:
    build: ./conf/common/docker/scepserver/
    entrypoint: /usr/local/bin/docker-entrypoint.py
    command: runserver
    environment:
      SCEP_CA_PASS: "CHANGE THIS, DO NOT USE IN PRODUCTION"
      SCEP_CERT_RENEW: 0  # Renewal always accepted
      ZENTRAL_API_SECRET: "eyJtb2R1bGUiOiJ6ZW50cmFsIn0:1eCDAx:ZPeW0awGnI-1iXZ2bzHC2IPMXnM"
      ZENTRAL_API_BASE_URL: "http://web:8000"
    volumes:
      - scep_ca:/var/lib/scep/CA
  nginx:
    depends_on:
      - promsrv
      - scepserver
      - web
    volumes:
      - ./conf/filebeat/docker/nginx/conf.d/:/etc/nginx/conf.d/
      - scep_ca:/scep_CA
  logstash:
    build: ./conf/filebeat/docker/logstash/
    ports:
      - "5044:5044"
    depends_on:
      - scepserver
    volumes:
      - scep_ca:/scep_CA
      - ./conf/start/docker/tls/:/zentral_tls

volumes:
  scep_ca:
